nhs-digital-gp-it-futures/BuyingCatalogueIdentity

.gitignore
=> Add developer signing credentials to .gitignore

src/NHSD.BuyingCatalogue.Identity.Api/Controllers/AccountController.cs, src/NHSD.BuyingCatalogue.Identity.Api/Services/ILoginService.cs, src/NHSD.BuyingCatalogue.Identity.Api/Services/LoginService.cs, src/NHSD.BuyingCatalogue.Identity.Api/Services/SignInResult.cs, src/NHSD.BuyingCatalogue.Identity.Api/Startup.cs, src/NHSD.BuyingCatalogue.Identity.Api/ViewModels/Account/LoginViewModel.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Builders/AccountControllerBuilder.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Builders/LoginServiceBuilder.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Controllers/AccountControllerTests.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/LoginServiceTests.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/LoginViewModelTests.cs
=> 3540 login unit tests

samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/Startup.cs, src/NHSD.BuyingCatalogue.Identity.Api/Settings/CookieExpirationSettings.cs, src/NHSD.BuyingCatalogue.Identity.Api/Startup.cs, src/NHSD.BuyingCatalogue.Identity.Api/appsettings.json
Adds configurable cookie expiration settings to the API project and hard-coded settings to the sample MVC client.
AB#5426
=> Add cookie expiration settings

src/NHSD.BuyingCatalogue.Identity.Api/Settings/ClientSetting.cs, src/NHSD.BuyingCatalogue.Identity.Api/Settings/ClientSettingCollection.cs, src/NHSD.BuyingCatalogue.Identity.Api/appsettings.Development.json, src/NHSD.BuyingCatalogue.Identity.Api/appsettings.json
=> Make access token lifetime configurable

src/NHSD.BuyingCatalogue.Identity.Api/Dockerfile, src/NHSD.BuyingCatalogue.Identity.Api/NHSD.BuyingCatalogue.Identity.Api.csproj, src/NHSD.BuyingCatalogue.Organisations.Api/Dockerfile
- do conversion from sass -> css in a node12 container
- remove extra 'src' directory
- base build steps on presence of css in wwwroot/css (output of npm run build)
=> 5519: Multistage build for ISAPI

src/NHSD.BuyingCatalogue.Identity.UserDatabase/Security/Users/NHSD.sql, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/DatabaseSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Utils/Database.cs
=> Apply more appropriate permissions to the NHSD user

README.md
Updated the readme with a brief description of all current endpoints and completed the section on running the integration tests.
AB#5490
=> Update the readme with all current endpoints

azure-pipelines.yml
This commit should prevent the pipeline failing because of a flaky assertion.
=> 3540 flaky assertion

docker-compose.yml
as they support TLS support out of the box
=> 5723: Switching to smtp4dev

tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Create User.5582.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Organisations GetAll 5146.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Organisations GetById 5147.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Utils/Database.cs
to stop relying on Bob & Alice accounts being there.
=> 5722: Refactored integration tests

azure-pipelines.yml
Creating isapi DB and also added the ACR for both Test and Prod
=> 5661 add isapi

src/NHSD.BuyingCatalogue.Organisations.Api/Errors/ApplicationUserErrors.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/Validators/ApplicationUserValidatorTests.cs
=> 6065: Fix email errors field

docker-compose.yml
=> Add SMTP server info to docker compose for identity

src/NHSD.BuyingCatalogue.Identity.Api/Controllers/AccountController.cs, src/NHSD.BuyingCatalogue.Identity.Api/Services/CreateBuyer/CreateBuyerService.cs, src/NHSD.BuyingCatalogue.Identity.Api/Services/IPasswordResetCallback.cs, src/NHSD.BuyingCatalogue.Identity.Api/Services/IPasswordService.cs, src/NHSD.BuyingCatalogue.Identity.Api/Services/IRegistrationService.cs, src/NHSD.BuyingCatalogue.Identity.Api/Services/PasswordResetCallback.cs, src/NHSD.BuyingCatalogue.Identity.Api/Services/PasswordService.cs, src/NHSD.BuyingCatalogue.Identity.Api/Services/RegistrationService.cs, src/NHSD.BuyingCatalogue.Identity.Api/Startup.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Send Email.3540.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/EmailSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Builders/AccountControllerBuilder.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Controllers/AccountControllerTests.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Services/CreateBuyerServiceTests.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Services/PasswordResetCallbackTests.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Services/PasswordServiceTests.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Services/RegistrationServiceTests.cs
=> Fix the password reset callback URL in the new user e-mail

src/NHSD.BuyingCatalogue.Identity.Api/Services/ProfileService.cs, src/NHSD.BuyingCatalogue.Identity.Common/Constants/ApplicationClaimTypes.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Login User Claims Validation.5447.feature, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Services/ProfileServiceTests.cs
Added Ordering Manage claim for Buyer
=> 6437 add buyer ordering claim

src/NHSD.BuyingCatalogue.Organisations.Api/NHSD.BuyingCatalogue.Organisations.Api.csproj
[AB#6342](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6342)
[AB#6197](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6197)
=> Treat warnings as errors in the Organisations API project

src/NHSD.BuyingCatalogue.Identity.Api/appsettings.Development.json, src/NHSD.BuyingCatalogue.Identity.Api/appsettings.json
[AB#6540](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6540)
[AB#6101](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6101)
=> Add Ordering scope to allowed scopes

tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/UserSteps.cs
[AB#6325](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6325)
=> 6325  ISAPI replaced the Password Hash method with dotnet core implementation

src/NHSD.BuyingCatalogue.Identity.Api/Views/Shared/_Layout.cshtml, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Accept Agreement UI Validation.3924.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Error UI Validation.3540.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Forgot Password Link Sent UI Validation.3926.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Forgot Password UI Validation.3926.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Login UI Validation.3540.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Registration UI Validation.4828.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password Confirmation UI Validation.3926.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password Expired UI Validation.3926.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password UI Validation.3926.feature
[AB#6390](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6390)
=> 6390: fixed logo link to now point at '/' also fixed label text

tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Drivers/EmailServerDriver.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Organisations Create 3536.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests.csproj, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/Common/Request.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/HealthCheckSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/OdsOrganisationSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/OrganisationsSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/UserSteps.cs
[AB#6287](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6287)
=> 6342 integration test http client refactor

azure-pipelines.yml
[AB#5542](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/5542)
- use latest .NET Core SDK
- update job display names to describe what they are doing more accurately
- stop building dev everytime
=> Fix specflow build fail

src/NHSD.BuyingCatalogue.Identity.Api/Views/Account/Registration.cshtml
Story: [AB#6945](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6945)
Task: [AB#6975](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6975)
=> 6945: Update content for registration page

src/NHSD.BuyingCatalogue.Identity.Api/Views/Account/Login.cshtml, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Login UI Validation.3540.feature
Story: [AB#6955](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6955)
Task: [AB#6978](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6978)
=> 6955: Update content for login page

src/NHSD.BuyingCatalogue.Identity.Api/Controllers/UsersController.cs, src/NHSD.BuyingCatalogue.Identity.Api/ViewModels/Users/CreateBuyerRequestModel.cs, src/NHSD.BuyingCatalogue.Identity.Api/ViewModels/Users/CreateBuyerResponseModel.cs, src/NHSD.BuyingCatalogue.Identity.Api/ViewModels/Users/GetAllOrganisationUsersModel.cs, src/NHSD.BuyingCatalogue.Identity.Api/ViewModels/Users/GetAllOrganisationUsersViewModel.cs, src/NHSD.BuyingCatalogue.Identity.Api/ViewModels/Users/GetUserModel.cs, src/NHSD.BuyingCatalogue.Identity.Api/ViewModels/Users/OrganisationUserModel.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Controllers/OdsController.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Controllers/OrganisationsController.cs, src/NHSD.BuyingCatalogue.Organisations.Api/ViewModels/Organisations/AddressModel.cs, src/NHSD.BuyingCatalogue.Organisations.Api/ViewModels/Organisations/CreateOrganisationRequestModel.cs, src/NHSD.BuyingCatalogue.Organisations.Api/ViewModels/Organisations/CreateOrganisationResponseModel.cs, src/NHSD.BuyingCatalogue.Organisations.Api/ViewModels/Organisations/GetAllOrganisationsModel.cs, src/NHSD.BuyingCatalogue.Organisations.Api/ViewModels/Organisations/GetAllOrganisationsViewModel.cs, src/NHSD.BuyingCatalogue.Organisations.Api/ViewModels/Organisations/OdsOrganisationModel.cs, src/NHSD.BuyingCatalogue.Organisations.Api/ViewModels/Organisations/OrganisationModel.cs, src/NHSD.BuyingCatalogue.Organisations.Api/ViewModels/Organisations/UpdateOrganisationModel.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Controllers/UsersControllerTests.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/Controllers/OrganisationControllerTests.cs
[AB#6257](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6257)
=> 6257: Rename viewmodels to model

docker-compose.yml, src/NHSD.BuyingCatalogue.Identity.Api/Controllers/AccountController.cs, src/NHSD.BuyingCatalogue.Identity.Api/Settings/PublicBrowseSettings.cs, src/NHSD.BuyingCatalogue.Identity.Api/appsettings.json, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Logout 3568.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/PublicBrowseSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Tools/WireMock/PublicBrowse/mappings/default-mapping.json, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Utils/Settings.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/appsettings.json
Story: [AB#7024](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7024)
Task: [AB#7027](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7027)
=> 7024: Fix default logout route

src/NHSD.BuyingCatalogue.Organisations.Api/Program.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Startup.cs
Story: [AB#7103](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7103)
Task [AB#7107](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7107)
=> 7107: PII flat set true in dev

src/NHSD.BuyingCatalogue.Organisations.Api/appsettings.json, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/TestContexts/OdsRepositoryTestContext.cs
[AB#7140](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7140)
=> Add GP and PCN ODS primary role IDs as buyer orgs

src/NHSD.BuyingCatalogue.Identity.Api/Services/ProfileService.cs, src/NHSD.BuyingCatalogue.Identity.Common/Constants/ApplicationPermissions.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Services/ProfileServiceTests.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Features/Ods Organisations GetByOdsCode 3536.feature, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Features/Organisations GetAll 5146.feature, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Features/Organisations GetById 5147.feature, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Steps/OrganisationsSteps.cs
Story: [AB#4615](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4615)
Task: [AB#7216](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7216)
=> Add organisation claim to buyer

src/NHSD.BuyingCatalogue.Identity.Api/appsettings.Development.json, src/NHSD.BuyingCatalogue.Identity.Api/appsettings.json
Tech debt task: [AB#6710](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6710)
=> Rename SampleClient to NodeClient

src/NHSD.BuyingCatalogue.Organisations.Api/Controllers/OrganisationsController.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Extensions/ClaimsPrincipalExtensions.cs, src/NHSD.BuyingCatalogue.Organisations.Api/ViewModels/Organisations/ServiceRecipientsModel.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Features/Organisations GetServiceRecipients.feature, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Steps/OrganisationServiceRecipientSteps.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/Builders/OrganisationBuilder.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/Builders/OrganisationControllerBuilder.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/Controllers/OrganisationControllerTests.cs
Story: [AB#7412](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7412)
Task: [AB#7466](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7466)
=> 7412: Get Service Recipients

samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/Controllers/HomeController.cs, samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/ViewModels/UserInfoViewModel.cs, samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/Views/Home/UserInfo.cshtml, src/NHSD.BuyingCatalogue.Organisations.Api/Controllers/OrganisationsController.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Models/OdsOrganisation.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Models/ServiceRecipient.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Repositories/IServiceRecipientRepository.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Repositories/ServiceRecipientRepository.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Settings/OdsSettings.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Startup.cs, src/NHSD.BuyingCatalogue.Organisations.Api/appsettings.json, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Features/Organisations GetServiceRecipients.feature, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Steps/OdsApiSteps.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Steps/OdsOrganisationSteps.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/Builders/OrganisationControllerBuilder.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/Builders/ServiceRecipientBuilder.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/Controllers/OrganisationControllerTests.cs
Story: [AB#4900](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4900)
Task: [AB#7657](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7657)
=> 7657: Implement search for Service Recipients

charts/isapi-db-deploy/templates/_helpers.tpl
[AB#6636](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6636)
[AB#7663](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7663)
=> Change job's name to allow re-deployments

charts/email/templates/_helpers.tpl, charts/isapi-db-deploy/templates/_helpers.tpl, charts/isapi/templates/_helpers.tpl, charts/oapi/templates/_helpers.tpl
[AB#6636](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6636)
[AB#7440](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7440)
=> Use local repository even when useLocalImage=false

src/NHSD.BuyingCatalogue.Organisations.Api/Repositories/ServiceRecipientRepository.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Features/Organisations GetServiceRecipients.feature, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/Repository/ServiceRecipientRepositoryTests.cs
Story: [AB#4900](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4900)
Task: [AB#7744](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7744)
=> 7744: Updated ServiceRecipientRepository to handle empty results

src/NHSD.BuyingCatalogue.Organisations.Api/Repositories/ServiceRecipientRepository.cs
Story: [AB#4900](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/4900)
Task: [AB#7925](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7925)
=> 7925: Updated ServiceRecipient query to only add offset if one exists

src/NHSD.BuyingCatalogue.Identity.UserDatabase/Deployment/CreateTestUsers.sql, tests/NHSD.BuyingCatalogue.Identity.Common.IntegrationTests/Utils/IntegrationDatabase.cs
STORY [AB#7839](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7839)
TASK   [AB#8065](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8065)
=> 8065: added test user  Sue at HULL CCG

src/NHSD.BuyingCatalogue.Identity.Api/Extensions/SwaggerExtensions.cs, src/NHSD.BuyingCatalogue.Identity.Api/NHSD.BuyingCatalogue.Identity.Api.csproj, src/NHSD.BuyingCatalogue.Identity.Api/Startup.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Extensions/SwaggerExtensions.cs, src/NHSD.BuyingCatalogue.Organisations.Api/NHSD.BuyingCatalogue.Organisations.Api.csproj, src/NHSD.BuyingCatalogue.Organisations.Api/Startup.cs
Story: [AB#8128](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8128)
Task: [AB#6873](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6873)
[AB#6874](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/6874)
=> 8128@ Swagger: ISAPI, OAPI

src/NHSD.BuyingCatalogue.Identity.Api/appsettings.Development.json, src/NHSD.BuyingCatalogue.Identity.Api/appsettings.json, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Accept Agreement UI Validation.3924.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Accept Agreement.3924.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Login with a valid client 3540.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Set New User Password.3540.feature
Story: [AB#7253](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7253)
Task: [AB#8475](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8475)
=> 8475: Disabled RequireConsent for all clients

samples/NHSD.BuyingCatalogue.Identity.Api.SampleClient/NHSD.BuyingCatalogue.Identity.Api.SampleClient.csproj, samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient.csproj, samples/NHSD.BuyingCatalogue.Identity.Api.SampleResource/NHSD.BuyingCatalogue.Identity.Api.SampleResource.csproj, src/NHSD.BuyingCatalogue.Identity.Api/NHSD.BuyingCatalogue.Identity.Api.csproj, src/NHSD.BuyingCatalogue.Identity.Common/NHSD.BuyingCatalogue.Identity.Common.csproj, src/NHSD.BuyingCatalogue.Organisations.Api/NHSD.BuyingCatalogue.Organisations.Api.csproj, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests.csproj, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/NHSD.BuyingCatalogue.Identity.Api.UnitTests.csproj, tests/NHSD.BuyingCatalogue.Identity.Common.IntegrationTests/NHSD.BuyingCatalogue.Identity.Common.IntegrationTests.csproj, tests/NHSD.BuyingCatalogue.Identity.Common.UnitTests/NHSD.BuyingCatalogue.Identity.Common.UnitTests.csproj, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests.csproj, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests.csproj
Story: [AB#8492](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8492)
Task: [AB#8786](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/8786)
Note: The Identity packages have a larger package update, but this would probably be wise extracting it out into another tech debt task
=> 8492: Update Nuget Packages

samples/NHSD.BuyingCatalogue.Identity.Api.SampleClient/NHSD.BuyingCatalogue.Identity.Api.SampleClient.csproj, samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient.csproj, samples/NHSD.BuyingCatalogue.Identity.Api.SampleResource/NHSD.BuyingCatalogue.Identity.Api.SampleResource.csproj, src/NHSD.BuyingCatalogue.Identity.Api/NHSD.BuyingCatalogue.Identity.Api.csproj, src/NHSD.BuyingCatalogue.Identity.Api/package-lock.json, src/NHSD.BuyingCatalogue.Identity.Common/NHSD.BuyingCatalogue.Identity.Common.csproj, src/NHSD.BuyingCatalogue.Organisations.Api/NHSD.BuyingCatalogue.Organisations.Api.csproj, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests.csproj, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/NHSD.BuyingCatalogue.Identity.Api.UnitTests.csproj, tests/NHSD.BuyingCatalogue.Identity.Common.IntegrationTests/NHSD.BuyingCatalogue.Identity.Common.IntegrationTests.csproj, tests/NHSD.BuyingCatalogue.Identity.Common.UnitTests/NHSD.BuyingCatalogue.Identity.Common.UnitTests.csproj, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests.csproj, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests.csproj
Story: [AB#9020](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9020)
Task: [AB#9019](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9019)
=> feature/9020-merge development-04082020

src/NHSD.BuyingCatalogue.Identity.Api/Views/Shared/_Layout.cshtml, src/NHSD.BuyingCatalogue.Identity.Api/appsettings.json, src/NHSD.BuyingCatalogue.Identity.Api/package-lock.json, src/NHSD.BuyingCatalogue.Identity.Api/package.json, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Accept Agreement UI Validation.3924.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Error UI Validation.3540.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Forgot Password Link Sent UI Validation.3926.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Forgot Password UI Validation.3926.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Login UI Validation.3540.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Registration UI Validation.4828.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password Confirmation UI Validation.3926.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password Expired UI Validation.3926.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password UI Validation.3926.feature
Story: [AB#9069](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9069)
Task: [AB#9483](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9483)
=> 9069: Update footer

src/NHSD.BuyingCatalogue.Identity.Api/Views/Shared/_Layout.cshtml, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Accept Agreement UI Validation.3924.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Error UI Validation.3540.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Forgot Password Link Sent UI Validation.3926.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Forgot Password UI Validation.3926.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Login UI Validation.3540.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Registration UI Validation.4828.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password Confirmation UI Validation.3926.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password Expired UI Validation.3926.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password UI Validation.3926.feature
Story: [AB#9069](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9069)
Task: [AB#9483](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9483)
=> 9069: Update footer PR Comment

src/NHSD.BuyingCatalogue.Identity.Api/Views/Shared/_Layout.cshtml
Story: [AB#9069](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9069)
Task: [AB#9483](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9483)
=> 9069: Update footer Fix

NHSD.BuyingCatalogue.Identity.sln, NHSD.BuyingCatalogue.Identity.sln.DotSettings, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Data/UserStore.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Drivers/EmailServerDriver.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Hooks/IntegrationHook.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests.csproj, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/AuthorisedSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/Common/CommonSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/Common/ErrorSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/DatabaseSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/EmailSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/HealthChecksSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/LoginSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/LogoutSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/OrganisationsSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/PasswordResetSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/PublicBrowseSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/RegistrationSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/UiInteractionSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/UiValidationSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/UserSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Utils/SeleniumContext.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Utils/Settings.cs, tests/NHSD.BuyingCatalogue.Identity.Api.Testing.Data/Entities/OrganisationEntity.cs, tests/NHSD.BuyingCatalogue.Identity.Api.Testing.Data/Entities/UserEntity.cs, tests/NHSD.BuyingCatalogue.Identity.Api.Testing.Data/EntityBuilder/OrganisationEntityBuilder.cs, tests/NHSD.BuyingCatalogue.Identity.Api.Testing.Data/Models/Address.cs, tests/NHSD.BuyingCatalogue.Identity.Api.Testing.Data/Models/GetUser.cs, tests/NHSD.BuyingCatalogue.Identity.Api.Testing.Data/NHSD.BuyingCatalogue.Identity.Api.Testing.Data.csproj
Activity: [AB#9815](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9815)
Task: [AB#11099](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11099)
=> Add StyleCop to Identity integration tests project

src/NHSD.BuyingCatalogue.Identity.Common/Models/ErrorDetails.cs, src/NHSD.BuyingCatalogue.Identity.Common/NHSD.BuyingCatalogue.Identity.Common.csproj, src/NHSD.BuyingCatalogue.Identity.Common/Results/Result.cs, src/NHSD.BuyingCatalogue.Identity.Common/Results/Result{T}.cs, src/NHSD.BuyingCatalogue.Identity.Common/ViewModels/Messages/ErrorMessageViewModel.cs, src/NHSD.BuyingCatalogue.Identity.UserDatabase.Deployment/NHSD.BuyingCatalogue.Identity.UserDatabase.Deployment.csproj, src/NHSD.BuyingCatalogue.Organisations.Api/Controllers/OdsController.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Controllers/OrganisationsController.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Data/ApplicationDbContext.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Data/OrganisationEntityTypeConfiguration.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Extensions/ClaimsPrincipalExtensions.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Extensions/SwaggerExtensions.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Logging/SerilogRequestLoggingOptions.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Models/Address.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Models/OdsOrganisation.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Models/OrganisationErrors.cs, src/NHSD.BuyingCatalogue.Organisations.Api/NHSD.BuyingCatalogue.Organisations.Api.csproj, src/NHSD.BuyingCatalogue.Organisations.Api/Repositories/OdsRepository.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Repositories/OrganisationRepository.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Repositories/ServiceRecipientRepository.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Services/CreateOrganisationRequest.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Services/CreateOrganisationService.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Settings/OdsSettings.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Startup.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Validators/IOrganisationValidator.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Validators/OrganisationValidator.cs, src/NHSD.BuyingCatalogue.Organisations.Api/ViewModels/Organisations/AddressModel.cs
Activity: [AB#9815](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9815)
Task: [AB#11099](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11099)
=> Add StyleCop to organisation and common projects

LICENCE, samples/NHSD.BuyingCatalogue.Identity.Api.SampleClient/NHSD.BuyingCatalogue.Identity.Api.SampleClient.csproj, samples/NHSD.BuyingCatalogue.Identity.Api.SampleClient/Program.cs, samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/Controllers/HomeController.cs, samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient.csproj, samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/Startup.cs, samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/ViewModels/UserInfoViewModel.cs, samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/Views/Home/Privacy.cshtml, samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/Views/Home/UserInfo.cshtml, samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/Views/Shared/_Layout.cshtml, samples/NHSD.BuyingCatalogue.Identity.Api.SampleResource/NHSD.BuyingCatalogue.Identity.Api.SampleResource.csproj, samples/NHSD.BuyingCatalogue.Identity.Api.SampleResource/Startup.cs
Activity: [AB#9815](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9815)
Task: [AB#11099](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11099)
=> Add StyleCop to samples

src/NHSD.BuyingCatalogue.Identity.Api/Views/Account/ForgotPassword.cshtml
Story: [AB#12166](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12166)
Task: [AB#12265](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12265)
=> Move error message on forgot pass

src/NHSD.BuyingCatalogue.Identity.Api/Views/Account/ForgotPassword.cshtml, src/NHSD.BuyingCatalogue.Identity.Api/Views/Account/ForgotPasswordLinkSent.cshtml, src/NHSD.BuyingCatalogue.Identity.Api/Views/Account/Login.cshtml, src/NHSD.BuyingCatalogue.Identity.Api/Views/Account/Registration.cshtml, src/NHSD.BuyingCatalogue.Identity.Api/Views/Account/ResetPassword.cshtml, src/NHSD.BuyingCatalogue.Identity.Api/Views/Account/ResetPasswordConfirmation.cshtml, src/NHSD.BuyingCatalogue.Identity.Api/Views/Account/ResetPasswordExpired.cshtml, src/NHSD.BuyingCatalogue.Identity.Api/Views/Consent/Index.cshtml, src/NHSD.BuyingCatalogue.Identity.Api/Views/Shared/Error.cshtml, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Accept Agreement UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Error UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Forgot Password Link Sent UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Forgot Password UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Login UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Registration UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password Confirmation UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password Expired UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password UI Validation.feature
To be a paragraph instead of H2
Story: [AB#12166](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12166)
Task: [AB#12259](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12259)
=> Refactor intro paragraph

charts/email/templates/ingress.yaml, charts/isapi/templates/ingress.yaml
Task: [AB#11823](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/11823)
Activity: [AB#13202](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13202)
=> Updated both ingress templates to v1

src/NHSD.BuyingCatalogue.Identity.UserDatabase/NHSD.BuyingCatalogue.Identity.UserDatabase.sqlproj, src/NHSD.BuyingCatalogue.Identity.UserDatabase/Tables/RelatedOrganisations.sql, src/NHSD.BuyingCatalogue.Organisations.Api/Controllers/OrganisationsController.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Data/ApplicationDbContext.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Models/Organisation.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Models/RelatedOrganisation.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Repositories/IOrganisationRepository.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Repositories/OrganisationRepository.cs, src/NHSD.BuyingCatalogue.Organisations.Api/ViewModels/Organisations/CreateRelatedOrganisationModel.cs, src/NHSD.BuyingCatalogue.Organisations.Api/ViewModels/Organisations/RelatedOrganisationModel.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/Builders/OrganisationBuilder.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/Builders/OrganisationControllerBuilder.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/Controllers/OrganisationControllerTests.cs
Added Get RelatedOrganisation, Get UnrelatedOrganisation and Create New RelatedOrganisation Endpoints
Story : [AB#12947](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12947)
=> Feature 12947 define proxy organisation relationships

src/NHSD.BuyingCatalogue.Organisations.Api/Controllers/OrganisationsController.cs, tests/NHSD.BuyingCatalogue.Identity.Api.Testing.Data/Entities/OrganisationEntity.cs, tests/NHSD.BuyingCatalogue.Identity.Common.IntegrationTests/Utils/IntegrationDatabase.cs, tests/NHSD.BuyingCatalogue.Identity.Common.IntegrationTests/Utils/Request.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Features/Organisations CreateRelatedOrganisation.feature, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Features/Organisations DeleteRelatedOrganisation.feature, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Features/Organisations GetRelatedOrganisations.feature, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Features/Organisations GetUnrelatedOrganisations.feature, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Steps/Common/CommonSteps.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.IntegrationTests/Steps/OrganisationsSteps.cs
Fix Access Policy on the Related Organisations Delete Endpoints
Update Specflow components to add in Related Organisations specific SpecFlow text
Add Integration Tests for all Related Organisation Endpoints
Story: [AB#12947](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12947)
Task: [AB#13815](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13815)
Story: [AB#12954](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12954)
Task: [AB#13879](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13879)
=> Feature 12947 12954 define proxy organisation relationships integration tests

src/NHSD.BuyingCatalogue.Identity.Api/Data/ApplicationDbContext.cs, src/NHSD.BuyingCatalogue.Identity.Api/Models/Organisation.cs, src/NHSD.BuyingCatalogue.Identity.Api/Models/RelatedOrganisation.cs, src/NHSD.BuyingCatalogue.Identity.Api/Repositories/OrganisationRepository.cs, src/NHSD.BuyingCatalogue.Identity.Api/Services/ProfileService.cs, src/NHSD.BuyingCatalogue.Identity.Common/Constants/ApplicationClaimTypes.cs
Story: [AB#12958](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12958)
Tasks:
[AB#13886](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13886)
[AB#12887](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12887)
=> Update Organisation Repository and Profile Service to Include Related Organisations

src/NHSD.BuyingCatalogue.Identity.Api/Services/ProfileService.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Login User Claims Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/AuthorisedSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Steps/OrganisationsSteps.cs, tests/NHSD.BuyingCatalogue.Identity.Api.Testing.Data/EntityBuilder/OrganisationEntityBuilder.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Builders/OrganisationBuilder.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Services/ProfileServiceTests.cs
Story: [AB#12958](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12958)
=> Add Unit and Integration tests for the relatedOrganisationId Claim Type

samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/Properties/launchSettings.json, samples/NHSD.BuyingCatalogue.Identity.Api.SampleMvcClient/appsettings.json, samples/NHSD.BuyingCatalogue.Identity.Api.SampleResource/Properties/launchSettings.json, samples/NHSD.BuyingCatalogue.Identity.Api.SampleResource/appsettings.json, src/NHSD.BuyingCatalogue.Identity.Api/Properties/launchSettings.json, src/NHSD.BuyingCatalogue.Identity.Api/appsettings.Development.json, src/NHSD.BuyingCatalogue.Organisations.Api/Properties/launchSettings.json, src/NHSD.BuyingCatalogue.Organisations.Api/appsettings.json
Activity: [AB#14240](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14240)
Task: [AB#14276](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14276)
=> Update launch settings to default to HTTPS

NHSD.BuyingCatalogue.Identity.sln.DotSettings, src/NHSD.BuyingCatalogue.Organisations.Api/Extensions/SwaggerExtensions.cs
Activity: [AB#14240](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14240)
Task: [AB#14278](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14278)
=> Fix swagger auth

src/NHSD.BuyingCatalogue.Organisations.Api/Controllers/OrganisationsController.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Extensions/ClaimsPrincipalExtensions.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/Builders/OrganisationControllerBuilder.cs, tests/NHSD.BuyingCatalogue.Organisations.Api.UnitTests/Controllers/OrganisationControllerTests.cs
Story: [AB#12959](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12959)
Task: [AB#13900](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13900)
=> update service recipients endpoint to include check for related organisation claims and add unit test to cover this

src/NHSD.BuyingCatalogue.Identity.Api/Views/Consent/Index.cshtml, src/NHSD.BuyingCatalogue.Identity.Api/Views/Shared/_Layout.cshtml, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Accept Agreement UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Error UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Forgot Password Link Sent UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Forgot Password UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Login UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Registration UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password Confirmation UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password Expired UI Validation.feature, tests/NHSD.BuyingCatalogue.Identity.Api.IntegrationTests/Features/Reset Password UI Validation.feature
Story [AB#13179](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/13179)
Task [AB#14663](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14663)
=> Update privacy policy page link

src/NHSD.BuyingCatalogue.Identity.Api/Controllers/ConsentController.cs, src/NHSD.BuyingCatalogue.Identity.Api/Extensions/HttpRequestExtensions.cs, src/NHSD.BuyingCatalogue.Identity.Api/Settings/CookieExpirationSettings.cs, src/NHSD.BuyingCatalogue.Identity.Api/Startup.cs, src/NHSD.BuyingCatalogue.Identity.Api/Views/Shared/_CookieConsent.cshtml, src/NHSD.BuyingCatalogue.Identity.Api/Views/Shared/_Layout.cshtml, src/NHSD.BuyingCatalogue.Identity.Api/appsettings.json, src/NHSD.BuyingCatalogue.Identity.Common/Constants/Cookies.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Controllers/ConsentControllerTests.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Extensions/HttpRequestExtensionsTests.cs
Bespoke Privacy and Cookie Banner
Check for privacy cookie existence
Create Privacy and Cookie Banner in ISAPI
Position partial for correcty layout
Update HTML for correct CSS
Use app setting to set the consent cookie expiration
Story: [AB#7250](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7250)
Task: [AB#14640](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14640),[AB#14647](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14647)
=> Policy cookie banner

src/NHSD.BuyingCatalogue.Identity.Api/Controllers/ConsentController.cs, src/NHSD.BuyingCatalogue.Identity.Api/Extensions/CookieData.cs, src/NHSD.BuyingCatalogue.Identity.Api/Extensions/HttpRequestExtensions.cs, src/NHSD.BuyingCatalogue.Identity.Api/Extensions/StringExtensions.cs, src/NHSD.BuyingCatalogue.Identity.Api/Settings/CookieExpirationSettings.cs, src/NHSD.BuyingCatalogue.Identity.Api/Views/Shared/_Layout.cshtml, src/NHSD.BuyingCatalogue.Identity.Api/appsettings.json, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Controllers/ConsentControllerTests.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Extensions/HttpRequestExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Extensions/StringExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/SharedMocks/MockRequestCookieCollection.cs
ISAPI - make cookie expirable by Env var
Story: [AB#7250](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7250)
Task: [AB#14970](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/14970)
=> Bespoke Privacy and Cookie Banner

src/NHSD.BuyingCatalogue.Identity.Api/Controllers/ConsentController.cs, src/NHSD.BuyingCatalogue.Identity.Api/Extensions/HttpRequestExtensions.cs, src/NHSD.BuyingCatalogue.Identity.Api/Extensions/StringExtensions.cs, src/NHSD.BuyingCatalogue.Identity.Api/Views/Shared/_CookieConsent.cshtml, src/NHSD.BuyingCatalogue.Organisations.Api/Data/OrganisationEntityTypeConfiguration.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Controllers/ConsentControllerTests.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Extensions/HttpRequestExtensionsTests.cs, tests/NHSD.BuyingCatalogue.Identity.Api.UnitTests/Extensions/StringExtensionsTests.cs
Story: [AB#12959](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12959)
Task: [AB#15230](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/15230)
=> Fix cookie content issue

src/NHSD.BuyingCatalogue.Identity.Api/Extensions/StringExtensions.cs, src/NHSD.BuyingCatalogue.Organisations.Api/Data/OrganisationEntityTypeConfiguration.cs
Story: [AB#12959](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/12959)
Task: [AB#15230](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/15230)
=> Make JSON deserialization case insensitive
